name: Run Laravel Pint

on:
  push:
    paths:
      - '**.php'

concurrency:
    group: build-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
  php-code-styling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Fix PHP code style issues
        uses: aglipanci/laravel-pint-action@1.0.0

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling
