name: Run Laravel Pint

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
  php-code-styling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fix PHP code style issues
        uses: aglipanci/laravel-pint-action@latest
        with:
          pintVersion: 1.18.1

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling
